#!/bin/zsh -l
#
# Install cs-bridge as a launchd agent.
#
# Run once. Afterwards the bridge starts with the Mac and the phone reaches it
# over Netbird. Re-running is safe: it refreshes the runner and the plist and
# leaves the existing token alone (use --new-token to rotate it).

emulate -L zsh
set -eu

here="${0:A:h}"
label="com.claudestudio.bridge"
support="$HOME/Library/Application Support/Claude Studio"
runner="$support/runners/$label.sh"
plist="$HOME/Library/LaunchAgents/$label.plist"
token_file="$support/bridge-token"
log="$support/bridge.log"

rotate=0
[[ "${1:-}" == "--new-token" ]] && rotate=1

mkdir -p "$support/runners" "$HOME/Library/LaunchAgents"

# --- ttyd -------------------------------------------------------------------

if ! command -v ttyd >/dev/null 2>&1; then
  print "Installing ttyd…"
  brew install ttyd
fi

# --- token ------------------------------------------------------------------
#
# Generated here and only here. The app reads this file to build its QR code;
# if both sides could create it they would eventually disagree.

if [[ $rotate -eq 1 || ! -s "$token_file" ]]; then
  umask 077
  /usr/bin/openssl rand -hex 32 > "$token_file"
  chmod 600 "$token_file"
  print "Token written to $token_file"
fi

# --- runner -----------------------------------------------------------------
#
# PATH is embedded rather than inherited: launchd hands an agent a minimal
# environment and `#!/bin/zsh -l` cannot be trusted to read .zshrc.

# An interactive shell runs the user's whole startup file, and a noisy plugin
# there must not abort the install — take the PATH if it comes, fall back if it
# does not.
user_path="$(/bin/zsh -l -i -c 'print -rn -- $PATH' 2>/dev/null || true)"
[[ -n "$user_path" ]] || user_path="$PATH"

cat > "$runner" <<RUNNER
#!/bin/zsh
# Generated by Bridge/install.sh — do not edit; re-run the installer instead.

export PATH='$user_path'

support="\$HOME/Library/Application Support/Claude Studio"
token="\$(cat "\$support/bridge-token" 2>/dev/null)"
[[ -n "\$token" ]] || { print -u2 "cs-bridge: no token"; exit 1 }

# Bind to the Netbird address only. If Netbird is not up yet there is no address
# to bind to, so exit and let launchd retry — never fall back to 0.0.0.0.
ip="\$(netbird status 2>/dev/null | awk '/NetBird IP:/ { print \$3 }' | cut -d/ -f1)"
[[ -n "\$ip" ]] || { print -u2 "cs-bridge: Netbird is not connected; retrying later"; exit 1 }

# Issue TLS material for whatever address Netbird handed out this time. The root
# is created once and reused; only the server certificate follows the address.
# Without HTTPS the phone gets a terminal but no notifications and no install.
'$here/make-cert.sh' "\$ip" || print -u2 "cs-bridge: certificate step failed; continuing on HTTP only"

# ttyd stays on loopback; the phone reaches it only through the bridge's /term
# proxy, so there is a single externally reachable port.
ttyd --port 7789 --interface lo0 --base-path /term \\
     --credential "cs:\$token" --url-arg --writable \\
     --terminal-type xterm-256color \\
     --client-option 'fontSize=13' \\
     --client-option 'scrollback=10000' \\
     '$here/cs-attach.sh' &
ttyd_pid=\$!
trap 'kill \$ttyd_pid 2>/dev/null' EXIT INT TERM

CS_BRIDGE_HOST="\$ip" exec node '$here/server.mjs'
RUNNER

chmod 755 "$runner"
chmod 755 "$here/cs-attach.sh"
chmod 755 "$here/make-cert.sh"

# --- launchd ----------------------------------------------------------------

cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/zsh</string>
    <string>$runner</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <!-- Netbird may come up after login; a slow retry lets the agent wait it out
       without spinning. -->
  <key>ThrottleInterval</key><integer>30</integer>
  <key>StandardOutPath</key><string>$log</string>
  <key>StandardErrorPath</key><string>$log</string>
</dict>
</plist>
PLIST

uid="$(id -u)"
launchctl bootout "gui/$uid/$label" 2>/dev/null || true
launchctl bootstrap "gui/$uid" "$plist"

print ""
print "cs-bridge installed."
ip="$(netbird status 2>/dev/null | awk '/NetBird IP:/ { print $3 }' | cut -d/ -f1)"
if [[ -n "$ip" ]]; then
  print "  http://$ip:7788/setup?k=$(cat "$token_file")"
  print ""
  print "Open Claude Studio → Settings → Phone to scan this as a QR code."
  print "The setup page walks through trusting the certificate once, which is what"
  print "notifications and installing it as an app depend on."
else
  print "  Netbird is not connected yet; the agent will start once it is."
fi
print "  Log: $log"
